name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check Code Style
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.30.0

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: kloeckner-i/db-auth-gateway:${{ github.sha }}
          outputs: type=docker,dest=/tmp/db-auth-gateway.tar
      - name: Upload docker image artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: /tmp/db-auth-gateway.tar

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: docker-image
          path: /tmp
      - name: Load Docker image
        run: docker load --input /tmp/db-auth-gateway.tar
      - name: Start Google Cloud SQL Mock and Dependencies
        run: |
          docker network create db-auth-gateway-test
          docker run -d --network=db-auth-gateway-test --network-alias=postgres --name=postgres -e "POSTGRES_PASSWORD=mysecretpassword" postgres:13
          docker run -d --network=db-auth-gateway-test --name=cloudsql_mock -p 127.0.0.1:3307:3307 -p 127.0.0.1:8080:8080 kloeckner-i/db-auth-gateway:${{ github.sha }} mock --db-address=postgres:5432 --instance=my-project:my-region:my-database
      - name: Test
        env:
          MOCK_ADDRESS: 127.0.0.1
        run: |
          make test e2e
      - name: Upload Test Logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-logs
          path: target/db-auth-gateway.log
      - name: Collect Docker Logs
        if: failure()
        uses: jwalton/gh-docker-logs@v1
        with:
          dest: './logs'
      - name: Tar Docker Logs
        if: failure()
        run: tar cvzf ./logs.tgz ./logs
      - name: Upload Docker Logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: docker-logs
          path: ./logs.tgz