name: example
on:
  push:

env:
  product_name: db-auth-proxy
  version: 1.0.0

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - {go: "1.17", goos: "linux", goarch: "amd64", dockerArch: "amd64"}
          - {go: "1.17", goos: "linux", goarch: "arm64", dockerArch: "arm64/v8"}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Compile Binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: '0'
        run: |
          go build -tags build -o "$product_name" .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and export
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          platforms: ${{ matrix.goos }}/${{ matrix.dockerArch }}
          tags: ghcr.io/allanger/db-auth-proxy:latest-${{ matrix.goarch }}
  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Load image
        run: |
            docker manifest create ghcr.io/allanger/db-auth-proxy:vlatest \
              --amend ghcr.io/allanger/db-auth-proxy:latest-amd64 \
              --amend ghcr.io/allanger/db-auth-proxy:latest-arm64
      - name: Load image
        run: |
          docker manifest push ghcr.io/allanger/db-auth-proxy:vlatest
      - name: Load image
        run: |
          docker inspect ghcr.io/allanger/db-auth-proxy:latest
