name: Tests

on:
  push:
  # branches:
  # - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check Code Style
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.46.2

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Test
        env:
          MOCK_ADDRESS: 127.0.0.1
        run: |
          # Separated to ensure the reset_mock target is executed between stages.
          make test
          make e2e
      
      - name: Upload Test Logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-logs
          path: target/db-auth-gateway.log
      
      - name: Collect Docker Logs
        if: failure()
        uses: jwalton/gh-docker-logs@v1
        with:
          dest: "./logs"
      
      - name: Tar Docker Logs
        if: failure()
        run: tar cvzf ./logs.tgz ./logs
      
      - name: Upload Docker Logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: docker-logs
          path: ./logs.tgz
